[project]
name = "suba-tomato"
version = "0.1.0"
description = "A super basic Pomodoro timer for the terminal."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "typer>=0.16.0",
]

[project.scripts]
tomato = "suba_tomato.main:app"